name: Github Actions
on: workflow_dispatch
jobs:
  Firstjobtesting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle analysis
        run: mvn checkstyle:checkstyle



    
